# This workflow will generate the docs on each push, and publish them on GitHub Pages if the branch is "master".

name: docs

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"

      - name: Install dependencies
        run: |
          sudo apt install pandoc
          uv sync --all-extras

      - name: Build Sphinx documentation
        run: |
          uv run sphinx-build -a -E -b html docs build

      - name: Deploy Sphinx documentation on Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/
