name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Python Package
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write  # Required for PyPI trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"  # Pin to specific uv version

      - name: Build package
        run: uv build --no-sources  # Recommended for production builds

      - name: Publish to PyPI
        run: uv publish -v dist/*
